### ISSUE TITLE
Upgrade to latest Channels

### ISSUE THREAD

**Issue by zerolab** [GrappleGQL/wagtail-grapple#86]
And upgrade to Channels 2.x for Django 3.0 support

Upgrade guide: https://channels.readthedocs.io/en/latest/one-to-two.html

**Comment by thclark** [comment]
So, channels 3.x is out - can I assume this should be called "Upgrade to latest version of Channels"?

Assuming I get time over the next few weeks, (a big assumption right now, might just have to go with wordpress for the sake of speed but would rather get set up properly with a wagtail cms) I think this would be my priority to fix. How would you propose it's done? My suggestion would be:

- [ ] A release allowing break of channels 1.x dependent code in favour of later version
- [ ] Update example to use channels 3
- [ ] Add async tests with pytest (Can't help but notice there's a bit of a lack of testing going on). It would need to be pytest rather than normal unittest because of asyncio capabilities.

**Comment by zerolab** [comment]
@thclark that sounds like a plan! Unfortunately I am not using it in any of the projects so cannot invest the time to take a deep dive with it yet.

👍 on a 1 release backwards compatibility with Channels 1.x if possible

**Comment by isolationism** [comment]
@thechark I'm interested in seeing this project updated to work with these new releases as well.

Looking at the roadmap, I don't see any obvious async features for 3.2; 3.0 vs. 3.1 represents a bit of a moving target from what I can see.

I agree there could use more testing in the project, though it's not a subject I'm particularly skilled at or comfortable with designing; I could see fixing/updating tests from a current version, but seeing none, and considering `channels` does not even seem to be in the requirement manifest, I'm uneasy about the scope of the work involved.

Anyone else interested and want to jump in?
